# Panda

#### complex data structure to mimic relational table in python

In [1]:
## Installion 
#import
import pandas as pd

In [3]:
list1 = [10,80,30.8,40.0,50,83,60]
print(type(list1))
s= pd.Series(list1)

print(type (s))
print(s)

<class 'list'>
<class 'pandas.core.series.Series'>
0    10.0
1    80.0
2    30.8
3    40.0
4    50.0
5    83.0
6    60.0
dtype: float64

In [5]:
## Series vs Dataframe
s2= pd.Series (["Math", "sc","ssc","art","music","eng","hindi"])
print(type(s2))
print(s2)

<class 'pandas.core.series.Series'>
0     Math
1       sc
2      ssc
3      art
4    music
5      eng
6    hindi
dtype: object

In [9]:
df1 = pd.DataFrame([s,s2])
data = [s,s2]
data

[0    10.0
 1    80.0
 2    30.8
 3    40.0
 4    50.0
 5    83.0
 6    60.0
 dtype: float64,
 0     Math
 1       sc
 2      ssc
 3      art
 4    music
 5      eng
 6    hindi
 dtype: object]

In [10]:
df2 = pd.DataFrame(data)
df2

      0     1     2     3      4     5      6
0  10.0  80.0  30.8  40.0   50.0  83.0   60.0
1  Math    sc   ssc   art  music   eng  hindi

In [12]:
df1 = pd.DataFrame(s,columns= ["Subject1", "Subject2","Subject3","Subject4", "Subject5","Subject6", "Subject7"])

ValueError: Shape of passed values is (7, 1), indices imply (7, 7)

In [ ]:
d1 = {
    ["Math":10],
    ["sc": 20],
    ["ssc":30],
    ["arts":50],
    ["eng":70],
    ["hindi": 90]
}
d1

SyntaxError: invalid syntax (3641752489.py, line 1)

In [14]:
df1= pd.DataFrame(d1)
df1

NameError: name 'd1' is not defined

In [ ]:
data =[
    [ "07-Jan-2026",	"Falcons",	"Comets",	"River Court"	," Zara",	"Grade", 6,	22,	29,	1	,3	,4,	2628,	"Coach Maya",	"Win"],
    [ "09-Jan-2026",	"Falcons",  "Comets",	"Central Dome",	"Zara",	"Grade", 5	,35,	12,	11,	14,	1,	2739,	"Coach Maya",	"Loss"]
]

df3 = pd.DataFrame(data,columns=['Match_Date','Team',	'Opponent',	'Venue',	'Player',	'Grade',	
                                 'Minutes_Played',	'Points_Scored',	'Assists',	'Rebounds',	'Fouls',	'Ticket_Sales',	'Coach',	'Match_Result',"extra"])
df3

,Match_Date,Team,Opponent,Venue,Player,Grade,Minutes_Played,Points_Scored,Assists,Rebounds,Fouls,Ticket_Sales,Coach,Match_Result,extra
0,07-Jan-2026,Falcons,Comets,River Court,Zara,Grade,6,22,29,1,3,4,2628,Coach Maya,Win
1,09-Jan-2026,Falcons,Comets,Central Dome,Zara,Grade,5,35,12,11,14,1,2739,Coach Maya,Loss

In [33]:
df4=pd.read_csv('/Users/manish/Downloads/apple_products_pricing_2020_2026.csv')
df4

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [49]:
data = pd.read_excel('/Users/manish/Downloads/customer_churn_data_raw.xlsx')
data

,customerid,name,country,state,gender,dob,interests,pincode
0,0002-ORFBO,keshav,India,Maharashtra,Male,1982-04-12,travel,NaN
1,0003-MKNFE,raghav,India,Karnataka,Male,1995-11-23,NaN,NaN
2,0004-TLHLJ,lalita,India,Delhi,Female,1978-02-15,movie,NaN
3,0011-IGKFF,mohan,India,Nagaland,Male,2001-08-30,NaN,NaN
4,0013-EXCHZ,mira,India,Delhi,Female,1990-05-05,drama,NaN
5,0013-MHZWF,durga,NaN,Delhi,Women,1988-12-10,NaN,NaN
6,0013-SMEOE,mina,India,Meghalaya,Female,1976-09-21,NaN,NaN
7,0014-BMAQU,madan,India,Rajasthan,Male,1999-03-14,NaN,NaN
8,0015-UOCOJ,maya,NaN,Kathmandu,Women,1985-07-07,NaN,NaN
9,0016-QLJIS,arjun,Nepal,Kathmandu,Male,1993-10-29,NaN,NaN
10,0017-DINOC,shiva,India,Maharashtra,Men,1997-01-22,NaN,NaN
11,0017-IUDMW,rangadevi,India,Karnataka,Female,1981-06-18,NaN,NaN
12,0018-NYROU,chitra,NaN,Telangana,Female,2004-12-01,NaN,NaN
13,0019-EFAEP,raju,India,Meghalaya,Female,1992-04-25,NaN,NaN
14,0019-GFNTW,Madhav,India,Uttar Pradesh,Men,1979-11-11,NaN,NaN
15,0020-INWCK,parvati,India,Delhi,Female,1986-02-28,job,NaN
16,0020-JDNXP,rikim,India,Meghalaya,Female,1994-08-19,NaN,NaN
17,0021-IKXGC,vishakha,India,Rajasthan,Female,2000-09-02,NaN,NaN
18,0022-TCJCI,raghvendra,India,Telangana,Male,1983-12-30,NaN,NaN
19,0023-HGHWL,rishabh,India,Uttar Pradesh,Men,1991-05-14,NaN,NaN
20,0023-UYUPN,sudevi,India,Maharashtra,Women,1977-10-06,NaN,NaN

In [56]:

## Summary stats using NumPy

import numpy as np

data = np.array(df4[df4.columns[6]][:39])

print(f"Count      : {data.size}")
print(f"Mean       : {np.mean(data):.2f}")
print(f"Median     : {np.median(data):.2f}")
print(f"Std (pop)  : {np.std(data):.2f}")              # Default: ddof=0 (population)
print(f"Std (sam)  : {np.std(data, ddof=1):.2f}")      # ddof=1 for sample
print(f"Var (pop)  : {np.var(data):.2f}")
print(f"Min        : {np.min(data)}")
print(f"Max        : {np.max(data)}")
print(f"Sum        : {np.sum(data)}")

# Percentiles
print(f"25th pctile: {np.percentile(data, 25):.2f}")
print(f"50th pctile: {np.percentile(data, 50):.2f}")   # Same as median
print(f"75th pctile: {np.percentile(data, 75):.2f}")
print(f"90th pctile: {np.percentile(data, 90):.2f}")

Count      : 39
Mean       : 44831.23
Median     : 42042.00
Std (pop)  : 10632.88
Std (sam)  : 10771.88
Var (pop)  : 113058212.23
Min        : 42042
Max        : 97902
Sum        : 1748418
25th pctile: 42042.00
50th pctile: 42042.00
75th pctile: 42042.00
90th pctile: 42042.00

In [57]:
df4.tail()

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
79995,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,861.39,82894.76,-1.5,NaN,In Stock,4.7,1346
79996,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,832.50,81159.39,1.9,NaN,In Stock,4.7,802
79997,2026-07-31,Amazon,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,657.30,56336.73,22.6,NaN,In Stock,4.2,1020
79998,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,Renewed/Refurbished,849,83202,709.49,61361.07,16.4,NaN,In Stock,3.9,710
79999,2026-07-31,Flipkart,iPhone,iPhone 17 128GB,New,849,83202,834.95,83035.30,1.7,NaN,Low Stock,4.8,1022

In [68]:

df5 = df4[:40][:]
df5

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35
5,2020-09-26,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.29,43149.46,-1.7,NaN,In Stock,4.7,45
6,2020-09-27,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.06,42587.59,-0.9,NaN,In Stock,4.8,60
7,2020-09-29,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,312.11,26276.64,27.2,NaN,In Stock,4.4,146
8,2020-10-01,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,323.84,31855.01,24.5,Big Billion Days,In Stock,4.7,95
9,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,390.51,38757.36,9.0,Great Indian Festival,In Stock,4.9,133
10,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,385.37,37753.37,10.2,Great Indian Festival,In Stock,4.5,57
11,2020-10-01,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,274.88,23070.56,35.9,Great Indian Festival,In Stock,4.5,99
12,2020-10-02,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,348.70,34771.74,18.7,Big Billion Days,In Stock,4.6,71
13,2020-10-03,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,324.80,32134.64,24.3,Big Billion Days,In Stock,4.9,62
14,2020-10-04,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,265.10,22614.35,38.2,Great Indian Festival,Low Stock,4.4,112
15,2020-10-06,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,348.69,33665.07,18.7,Great Indian Festival,Out of Stock,4.4,127
16,2020-10-06,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,380.46,36957.63,11.3,Great Indian Festival,In Stock,4.6,112
17,2020-10-06,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,354.95,34964.38,17.3,Big Billion Days,In Stock,4.7,176
18,2020-10-07,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,348.33,34539.69,18.8,Big Billion Days,In Stock,4.7,140
19,2020-10-07,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,308.34,25820.76,28.1,Big Billion Days,Out of Stock,4.0,157
20,2020-10-08,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,351.25,34046.78,18.1,Big Billion Days,Out of Stock,4.2,163
21,2020-10-08,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,338.18,33386.67,21.2,Big Billion Days,Low Stock,4.6,160
22,2020-10-09,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,373.25,36495.14,13.0,Big Billion Days,In Stock,4.6,44
23,2020-10-11,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,370.68,36046.07,13.6,Great Indian Festival,In Stock,4.8,97
24,2020-10-11,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,340.08,33597.58,20.7,Great Indian Festival,In Stock,4.5,102
25,2020-10-14,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,328.53,32762.66,23.4,Big Billion Days,Out of Stock,4.3,156
26,2020-10-14,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,287.87,24767.07,32.9,Big Billion Days,Out of Stock,3.9,225
27,2020-10-15,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,255.77,21918.92,40.4,Big Billion Days,Low Stock,4.0,135
28,2020-10-16,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.39,42886.43,-0.1,NaN,In Stock,4.8,168
29,2020-10-18,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,331.95,28468.19,22.6,NaN,In Stock,4.3,225
30,2020-10-18,Flipkart,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,360.84,30701.30,15.9,NaN,In Stock,3.8,184
31,2020-10-21,Amazon,Watch,Apple Watch Series 6 (44mm),Renewed/Refurbished,429,42042,360.47,30502.87,16.0,NaN,In Stock,4.4,147
32,2020-10-22,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,437.28,43200.77,-1.9,NaN,In Stock,4.4,158
33,2020-10-23,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,433.40,42014.16,-1.0,NaN,In Stock,4.7,186
34,2020-10-23,Flipkart,iPad,iPad Air (4th Gen) 64GB,New,599,58702,599.55,58434.06,-0.1,NaN,Out of Stock,4.6,83
35,2020-10-23,Flipkart,iPhone,iPhone 12 64GB,New,799,78302,794.53,78340.42,0.6,NaN,In Stock,4.4,87
36,2020-10-23,Flipkart,iPhone,iPhone 12 Pro 128GB,New,999,97902,994.04,97853.88,0.5,NaN,In Stock,4.2,73
37,2020-10-24,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,421.78,40536.55,1.7,NaN,In Stock,4.6,140
38,2020-10-24,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,429.40,42578.05,-0.1,NaN,Low Stock,4.3,168
39,2020-10-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,424.81,42357.77,1.0,NaN,Out of Stock,4.3,263

In [69]:
df4.head(5)

,Date,Platform,Product_Category,Model_Name,Condition,Launch_Price_USD,Launch_Price_INR,Current_Price_USD,Current_Price_INR,Discount_Pct,Sale_Event,Stock_Status,Rating,Reviews_Count
0,2020-09-19,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,435.81,43322.41,-1.6,NaN,In Stock,4.7,40
1,2020-09-20,Flipkart,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.49,42320.43,-1.7,NaN,Out of Stock,4.6,84
2,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,422.73,40879.36,1.5,NaN,In Stock,4.4,110
3,2020-09-23,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,425.00,42008.70,0.9,NaN,In Stock,4.8,111
4,2020-09-24,Amazon,Watch,Apple Watch Series 6 (44mm),New,429,42042,436.22,41984.28,-1.7,NaN,In Stock,4.7,35

In [70]:
df4.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 80000 entries, 0 to 79999
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               80000 non-null  object
 1   Platform           80000 non-null  object
 2   Product_Category   80000 non-null  object
 3   Model_Name         80000 non-null  object
 4   Condition          80000 non-null  object
 5   Launch_Price_USD   80000 non-null  int64
 6   Launch_Price_INR   80000 non-null  int64
 7   Current_Price_USD  80000 non-null  float64
 8   Current_Price_INR  80000 non-null  float64
 9   Discount_Pct       80000 non-null  float64
 10  Sale_Event         6649 non-null   object
 11  Stock_Status       80000 non-null  object
 12  Rating             80000 non-null  float64
 13  Reviews_Count      80000 non-null  int64
dtypes: float64(4), int64(3), object(7)
memory usage: 8.5+ MB

In [72]:
df4.describe

<bound method NDFrame.describe of              Date  Platform Product_Category                   Model_Name  \
0      2020-09-19  Flipkart            Watch  Apple Watch Series 6 (44mm)
1      2020-09-20  Flipkart            Watch  Apple Watch Series 6 (44mm)
2      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)
3      2020-09-23    Amazon            Watch  Apple Watch Series 6 (44mm)
4      2020-09-24    Amazon            Watch  Apple Watch Series 6 (44mm)
...           ...       ...              ...                          ...
79995  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79996  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79997  2026-07-31    Amazon           iPhone              iPhone 17 128GB
79998  2026-07-31  Flipkart           iPhone              iPhone 17 128GB
79999  2026-07-31  Flipkart           iPhone              iPhone 17 128GB

                 Condition  Launch_Price_USD  Launch_Price_INR  \
0                      New               429             42042
1                      New               429             42042
2                      New               429             42042
3                      New               429             42042
4                      New               429             42042
...                    ...               ...               ...
79995                  New               849             83202
79996                  New               849             83202
79997  Renewed/Refurbished               849             83202
79998  Renewed/Refurbished               849             83202
79999                  New               849             83202

       Current_Price_USD  Current_Price_INR  Discount_Pct Sale_Event  \
0                 435.81           43322.41          -1.6        NaN
1                 436.49           42320.43          -1.7        NaN
2                 422.73           40879.36           1.5        NaN
3                 425.00           42008.70           0.9        NaN
4                 436.22           41984.28          -1.7        NaN
...                  ...                ...           ...        ...
79995             861.39           82894.76          -1.5        NaN
79996             832.50           81159.39           1.9        NaN
79997             657.30           56336.73          22.6        NaN
79998             709.49           61361.07          16.4        NaN
79999             834.95           83035.30           1.7        NaN

       Stock_Status  Rating  Reviews_Count
0          In Stock     4.7             40
1      Out of Stock     4.6             84
2          In Stock     4.4            110
3          In Stock     4.8            111
4          In Stock     4.7             35
...             ...     ...            ...
79995      In Stock     4.7           1346
79996      In Stock     4.7            802
79997      In Stock     4.2           1020
79998      In Stock     3.9            710
79999     Low Stock     4.8           1022

[80000 rows x 14 columns]>